### ISSUE TITLE
PHP isnt accessible in my environment at all

### ISSUE THREAD

**Issue by borngreat-ikwutah** [abdielwilsn/zenotes#8]
I installed XAMPP
![Screenshot 2024-09-23 143608](https://github.com/user-attachments/assets/3ca35144-ad5c-4730-baa1-ec7b7c0f2231)
, started the Apache server and tried typing PHP -v it didn't work on my Gitbash terminal at all...

**Comment by abdielwilsn** [comment]
https://herd.laravel.com/windows 

try this
